//===========================================================================
//
//  sgl2 言語　文法 
//
//---------------------------------------------------------------------------

{
  
}

//-------------------------------------------------------------------------
//  Constants (定数)
//-------------------------------------------------------------------------

// １６進リテラル

HexIntegerConstant  = HexPrefix HexDetail+ HexSuffix IntegerSuffix?
HexDetail = HexDigit / '%0020'
HexPrefix       = '0x'
HexSuffix       = 'x'
HexDigit        = [a-f] / [A-F] / [0-9]


// 

IntegerSuffix
   = UnsignedSuffix? ByteSizeSuffix

ByteSizeSuffix = ByteSuffix / WordSuffix / LongSuffix

ByteSuffix      = 's'
WordSuffix      = 'w'
LongSuffix      = 'l'
UnsignedSuffix  = 'u'


